name = "portfolio-website"
pages_build_output_dir = "dist"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "portfolio-website-db"
database_id = "8cfa1c0e-83ed-47d5-9142-5d02c00fd690"
